name: Diabeties_prediction

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main



jobs:
  Diabeties_prediction:
    runs-on: python:3.14
  

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up python environment
        uses: actions/checkout@v4
        with:
          python-version: 3.14

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          python train.py

  Docker_build:
    needs: Diabeties_prediction
    runs-on: python:3.14
  
    steps:
      - name:  checkout code
        uses:  actions/checkout@v4

      - name:  set up docker Docker_build
        uses:  docker/setup-buildx-action@v2

      - name:  login to docker
        uses:  docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name:  Docker build
        run:  docker build . --file Dockerfile --tag prediction:$(date +%s)

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/prediction-app:latest


      - name:  Image digest
        run:  echo ${{ steps.build-and-publish.outputs.digest }}
          

   
